name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - "solutions/CUCore"

stages:
  - template: ../stages/build-managed.yml
    parameters: 
      SolutionContentDirectory: "solutions\\CUCore\\content"
      SolutionName: "CUCore"
      TargetEnvironment: $(powerAppsEnvironment)
  - template: ../stages/release-managed.yml
    parameters: 
      SolutionContentDirectory: "solutions\\CUCore\\content"
      SolutionName: "CUCore"
      TargetEnvironment: $(powerAppsEnvironment)