name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - "solutions/TestSolution"

stages:
  - template: ../stages/build-and-release.yml
    parameters: 
      SolutionContentDirectory: "solutions/TestSolution"
      SolutionName: "TestSolution"
      TargetEnvironment: "test-environment"