name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - "solutions/CUAdmissions"

stages:
  - template: ../stages/build-managed.yml
    parameters: 
      SolutionContentDirectory: "solutions\\CUAdmissions\\content"
      SolutionName: "CUAdmissions"
      TargetEnvironment: $(powerAppsEnvironment)
  - template: ../stages/release-managed.yml
    parameters: 
      SolutionContentDirectory: "solutions\\CUAdmissions\\content"
      SolutionName: "CUAdmissions"
      TargetEnvironment: $(powerAppsEnvironment)
  - stage: Import_Config_Data
    jobs:
      - job:
        pool:
          vmimage: 'vs2017-win2016'
        steps:
        # Import from static file
        - template: ../steps/configuration-migration.yml
          parameters:
            userName: $(userName)
            userPassword: $(userPassword)
            serverUrl: $(serverUrl)
            dataFile: 'solutions\CUAdmissions\data\admissions-student-application-data.zip'
