name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

variables: 
  SolutionContentDirectory: "solutions/CUAdmissions"

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - ${{ variables.SolutionContentDirectory }}

stages:
  - template: ../stages/build-and-release.yml
    parameters: 
      SolutionContentDirectory: ${{ variables.SolutionContentDirectory }}
      SolutionName: "CUAdmissions"
      TargetEnvironment: "release-target"