trigger: none

variables:
  SolutionName: CUAdmissions
  ArtifactName: solution-artifact

stages:
  - stage: Export_Solutions
    jobs:
      - template: ../jobs/solution-export/parallel-export.yml
        parameters:
          ArtifactName: ${{ variables.ArtifactName }}
          Environment: $(Environment)
          SolutionName: ${{ variables.SolutionName }}
  - stage: Commit_Solutions
    dependsOn: Export_Solutions
    jobs:
      - template: ../jobs/solution-unpack/solution-unpack-commit.yml
        parameters:
          ArtifactName: ${{ variables.ArtifactName }}
          SolutionName: ${{ variables.SolutionName }}
