name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)
trigger: none

jobs:
- job:
  pool: 
    vmimage: "vs2017-win2016"

  steps:
    - task: PowerShell@2
      inputs:
        filePath: '$(Build.SourcesDirectory)\pipelines\powershell\import-data.ps1'
        arguments: '-userName $(userName) -userPassword $(userPassword) -serverUrl $(serverUrl) -dataFile $(datafile)'
      