name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger: none

stages:
  - template: ../stages/build-and-sync-dev.yml
    parameters: 
      SolutionContentDirectory: "solutions/CUAdmissions"
      SolutionName: "CUAdmissions"
      TargetEnvironment: "admissions_dev"