name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger: none

stages:
  - template: ../stages/build-unmanaged.yml
    parameters: 
      SolutionContentDirectory: "solutions/CUAdmissions/content"
      SolutionName: "CUAdmissions"
      TargetEnvironment: "admissions_dev"
  - template: ../stages/release-unmanaged.yml
    parameters: 
      SolutionContentDirectory: "solutions/CUAdmissions/content"
      SolutionName: "CUAdmissions"
      TargetEnvironment: "admissions_dev"