name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger: none

stages:
  - template: ../stages/build-and-release.yml
    parameters: 
      SolutionContentDirectory: "solutions/CUCore/content"
      SolutionName: "CUCore"
      TargetEnvironment: "admissions_dev"
    #TODO re-write release code to build once and deploy to many environments for syncing dev instances.