name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger: none

stages:
  # Admissions
  - template: ../stages/build-unmanaged.yml
    parameters: 
      SolutionContentDirectory: "solutions/CUCore"
      SolutionName: "CUCore"
      TargetEnvironment: "admissions_dev"
  - template: ../stages/release-unmanaged.yml
    parameters: 
      SolutionContentDirectory: "solutions/CUCore"
      SolutionName: "CUCore"
      TargetEnvironment: "admissions_dev"
  
  # Financial Aid
  - template: ../stages/build-unmanaged.yml
    parameters: 
      SolutionContentDirectory: "solutions/CUCore"
      SolutionName: "CUCore"
      TargetEnvironment: "finAid_dev"
  - template: ../stages/release-unmanaged.yml
    parameters: 
      SolutionContentDirectory: "solutions/CUCore"
      SolutionName: "CUCore"
      TargetEnvironment: "finAid_dev"