name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger:
  batch: true
  branches:
    include:
      - development
  paths:
    include:
      - "solutions/CUCore"

stages:
  - template: ../stages/build-managed.yml
    parameters: 
      SolutionContentDirectory: "solutions/CUCore/content"
      SolutionName: "CUCore"
      TargetEnvironment: "admissions_dev"

# Release
  - template: ../stages/release-managed.yml
    parameters: 
      SolutionContentDirectory: "solutions/CUCore/content"
      SolutionName: "CUCore"
      TargetEnvironment: "admissions_dev"
    
  - template: ../stages/release-managed.yml
    parameters: 
      SolutionContentDirectory: "solutions/CUCore/content"
      SolutionName: "CUCore"
      TargetEnvironment: "finAid_dev"