name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger:
  batch: true
  branches:
    include:
      - development
  paths:
    include:
      - "solutions/CUCore"

stages:
  - template: ../stages/build-managed.yml
    parameters: 
      SolutionContentDirectory: "solutions\\CUCore\\content"
      SolutionName: "CUCore"
      TargetEnvironment: "admissions_dev"

# Parallelized Release
  - stage: Deploy_CUCore
    jobs:
      - template : ../jobs/release/release-solution.yml
        parameters: 
            SolutionContentDirectory: "solutions\\CUCore\\content"
            SolutionName: "CUCore"
            TargetEnvironment: "admissions_dev"
            solutionType: Managed
      - template : ../jobs/release/release-solution.yml  
        parameters: 
          SolutionContentDirectory: "solutions\\CUCore\\content"
          SolutionName: "CUCore"
          TargetEnvironment: "finAid_dev"
          solutionType: Managed