trigger: none

stages:
  - stage: Export_Solutions
    jobs:
      - template: jobs/solution-export/parallel-export.yml
        parameters:
          artifactName: "solution-artifact"
          environment: $(Environment)
          SolutionsName: $(SolutionName)
      - template: jobs/solution-unpack/solution-unpack.yml
        parameters:
          artifactName: "solution-artifact"
          SolutionsName: $(SolutionName)

  - stage: Commit_Solutions
    dependsOn: Export_Solutions
    jobs:
      - template: jobs/solution-export/aggregate-commit.yml
        parameters:
          artifactName: "solution-artifact"
          solutions: $(SolutionName)
