trigger: none
variables:
  SolutionName:
    - CUCore
    - CUAdmissions

stages:
  - stage: Export_Solutions
    jobs:
      - template: jobs/solution-export/parallel-export.yml
        parameters:
          artifactName: "solution-artifact"
          environment: $(Environment)
          solutions: $(SolutionName)
  - stage: Commit_Solutions
    dependsOn: Export_Solutions
    jobs:
      - template: jobs/solution-export/aggregate-commit.yml
        parameters:
          artifactName: "solution-artifact"
          solutions: $(SolutionName)
