trigger: none
variables:
  SolutionName: CUCore

stages:
  - stage: Export_Solutions
    jobs:
      - template: jobs/solution-export/parallel-export.yml
        parameters:
          artifactName: "solution-artifact"
          environment: $(Environment)
          solutions:
            - ${{ variables.SolutionName }}
  - stage: Commit_Solutions
    dependsOn: Export_Solutions
    jobs:
      - template: jobs/solution-export/aggregate-commit.yml
        parameters:
          artifactName: "solution-artifact"
          solutions:
            - ${{ variables.SolutionName }}
