parameters:
  artifactName: ''
  environments: ''
  solutions: []

jobs:
- ${{ each solution in parameters.solutions }}:
  - template: export.yml
    parameters:
      artifactName: ${{ parameters.artifactName }}
      environment: ${{ environment }}
      solutionName: ${{ parameters.solutionName }}