# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerAppsToolInstaller@0

- task: PowerAppsPackSolution@0
  inputs:
    SolutionSourceFolder: 'solutions\CUCore\content'
    SolutionOutputFile: '$(Pipeline.Workspace)/packed-solutions/core.zip'

- publish: $(Pipeline.Workspace)/packed-solutions
  artifact: solution-artifact