parameters: 
  solutions: []
  powerAppsEnvironment: ''
  userName: ''
  userPassword: ''
  serverUrl: ''

# Deploy many solutions and migrate config data in sequence based on input array 
# Example input
#  parameters:
#     solutions: [
#             {
#               name: "ExampleManagedDependency_1_0_0_0_managed.zip",
#               directory: "solutions/ExampleManagedDependency",
#               dataFiles: ["solutions/ExampleManagedDependency/data/configuration-data.zip"]
#             },
#             {
#               name: "ExampleManagedDependencyNoData_1_0_0_0_managed.zip",
#               directory: "solutions/ExampleManagedDependencyNoData",
#             },
#             {
#               dataFiles: ["solutions/ExampleManagedDependency/data/configuration-data.zip"]
#             }
#            ]
jobs:
 - job: Deploy_Managed_Dependencies
   pool:
     vmimage: "vs2017-win2016"
   steps:
    - task: PowerAppsToolInstaller@0

    - ${{ each solution in parameters.solutions }}:
      - ${{ if ne(solution.name, '') }}:
        - task: PowerAppsImportSolution@0
          inputs:
            PowerAppsEnvironment: ${{ parameters.powerappsEnvironment }}
            SolutionInputFile: ${{ solution.directory }}/${{ solution.name }}
            AsyncOperation: true
            MaxAsyncWaitTime: '240'
          displayName: Import ${{ solution.name }} solution
      - ${{ each datafile in solution.dataFiles }}:
        # Import from static file
        - template: ../steps/configuration-migration.yml
          parameters:
            dataFile: ${{ datafile }}
            userName: ${{ parameters.userName }}
            userPassword: ${{ parameters.userPassword }}
            serverUrl: ${{ parameters.serverUrl }}