parameters:
  SolutionContentDirectory: ""
  SolutionName: ""
  TargetEnvironment: ""

stages:
  - stage: Build_${{ parameters.SolutionName }}

    jobs:
      - template: ../jobs/build/build-solution.yml
        parameters:
          SolutionContentDirectory: ${{ parameters.SolutionContentDirectory }}
          SolutionName: ${{ parameters.SolutionName }}
          TargetEnvironment: ${{ parameters.TargetEnvironment }}
          SolutionType: "Managed"