parameters:
    SolutionContentDirectory: ""
    SolutionName: ""
    TargetEnvironment: ""

stages:
  - stage: Release_To_${{ parameters.TargetEnvironment }}

    jobs:
      - template: ../jobs/release/release-solution.yml
        parameters:
          SolutionContentDirectory: ${{ parameters.SolutionContentDirectory }}
          SolutionName: ${{ parameters.SolutionName }}
          TargetEnvironment: ${{ parameters.TargetEnvironment }}
          SolutionType: "Unmanaged"
