name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger: none

stages:
- stage: Create_Environment
  displayName: Create Environment
  jobs: 
  - job: Create_Dev_Core

    pool:
      vmImage: "vs2017-win2016"

    steps:

    - script: echo "Hello, world!"