name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger: none

stages:
- stage: Create_Environment
  displayName: Create Environment
  jobs: 
  - job: Create_Dev_Core

    pool:
      vmImage: "vs2017-win2016"

    steps:

    - script: echo "Hello, world!"

    - pwsh: |
        Install-Module Microsoft.Xrm.OnlineManagementAPI

    - pwsh: |
        Get-CrmInstances -ApiUrl "https://admin.services.crm.dynamics.com" -Credential (Get-Credential)

    # - task: PowerAppsCreateEnvironment@0
    #   inputs:
    #     PowerAppsAdminCredentials: 'Admin API Service'
    #     DeploymentRegion: 'https://admin.services.crm.dynamics.com'
    #     DomainName: 'meecrosoft'
    #     FriendlyName: 'CoreDevelopmentEnvironment'
    #     TargetRelease: bce9abbf-90fd-42e7-b0e5-1ced6df22fa1
    #     InstanceType: Sandbox
    #     BaseLanguage: 1033
