name: $(Build.DefinitionName)-$(Build.SourceBranch)-$(Date:yyyyMMdd)

trigger: none

stages:
- stage: Create_Environment
  displayName: Create Environment
  jobs: 
  - job: Create_Dev_Core

    pool:
      vmImage: "vs2017-win2016"

    steps:

    - script: echo "Hello, world!"

    - powershell: |
        Install-Module Microsoft.Xrm.OnlineManagementAPI

    - powershell: |
        $SecurePassword  = convertto-securestring $(account.password) -asplaintext -force
        $Cred = New-Object System.Management.Automation.PSCredential ("$(account.username)", $SecurePassword)
        Get-CrmInstances -ApiUrl "https://admin.services.crm.dynamics.com" -Credential $Cred