parameters:
  artifactName: "solution-artifact"
  solutionName: ""

jobs:
  - job: Aggregate_Commit
    pool:
      vmImage: "vs2017-win2016"
    dependsOn: Unpack_Solutions
    steps:
      - checkout: self
        persistCredentials: true

      # Reattach to branch (variable)
      # Configure user.name and user.email
      - pwsh: |
          git checkout ("$(Build.SourceBranch)" -replace "^refs/heads/", "")
          git config user.name "Automated Pipeline Commit"
          git config user.email "PPALM-Exploration-Build-Account"
        displayName: "Checkout branch and config user"

      - download: current

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Pipeline.Workspace)/${{ parameters.artifactName }}-${{ parameters.SolutionName }}/unpacked"
          Contents: "**"
          TargetFolder: "$(Build.SourcesDirectory)/solutions"
          OverWrite: true

      - script: |
          git add .
          git commit -m "Automated commit of solutions: ${{ join(', ', parameters.solutions) }}"
          git push
        displayName: "Automated commit of solutions: ${{ join(', ', parameters.solutions) }}"
      # TODO ensure project collection build service accounts has contribute permissions
