parameters:
  artifactName: "solution-artifact"
  solutions: []

jobs:
  - job: AggregateCommit
    displayName: "Aggregate Commit"

    pool:
      vmImage: "vs2017-win2016"

    steps:
      - download: current

      - ${{ each solution in parameters.solutions }}:
          - task: CopyFiles@2
            inputs:
              SourceFolder: "$(Pipeline.Workspace)/${{ parameters.artifactName }}-${{ solution }}/unpacked"
              Contents: "**"
              TargetFolder: "$(Build.SourcesDirectory)/solutions"
              OverWrite: true

      - task: PowerShell@2
        inputs:
          targetType: "inline"
          script: |
            cd $(Build.SourcesDirectory)/solutions
            dir

      - publish: $(Build.SourcesDirectory)/solutions
        artifact: EXAMPLE-COMMIT

      - checkout: self
        persistCredentials: true
      # Reattach to branch (variable)
      # Configure user.name and user.email
      # Commit
      # Push
      # project collection build service accounts.
      # Has contribute permissions
