parameters:
  artifactName: "solution-artifact"
  solutions: []

jobs:
  - job: AggregateCommit
    displayName: "Aggregate Commit"

    pool:
      vmImage: "vs2017-win2016"

    steps:
      - checkout: self
        persistCredentials: true

      # Reattach to branch (variable)
      # Configure user.name and user.email
      - pwsh: |
          git checkout ($(Build.SourceBranch) -replace "^refs/heads/", "")
          git config user.name "Test User"
          git config user.email "Test@test.com"

      - download: current

      - ${{ each solution in parameters.solutions }}:
          - task: CopyFiles@2
            inputs:
              SourceFolder: "$(Pipeline.Workspace)/${{ parameters.artifactName }}-${{ solution }}/unpacked"
              Contents: "**"
              TargetFolder: "$(Build.SourcesDirectory)/solutions"
              OverWrite: true

      - task: PowerShell@2
        inputs:
          targetType: "inline"
          script: |
            cd $(Build.SourcesDirectory)/solutions
            dir

      - publish: $(Build.SourcesDirectory)/solutions
        artifact: EXAMPLE-COMMIT

      - script: |
          git add .
          git commit -m "Automated commit of solutions: ${{ join(', ', parameters.solutions) }}"
          git push
      # TODO ensure project collection build service accounts has contribute permissions
