parameters:
  artifactName: "solution-artifact"
  environment: ""
  solutionName: ""

jobs:
  - job: Export_${{ parameters.solutionName }}
    pool:
      vmImage: "vs2017-win2016"

    steps:
      - task: PowerAppsToolInstaller@0

      - task: PowerAppsExportSolution@0
        inputs:
          SolutionName: "${{ parameters.solutionName }}"
          SolutionOutputFile: '$(Pipeline.Workspace)\${{ parameters.artifactName }}\packed\${{ parameters.solutionName }}.zip'
          PowerAppsEnvironment: "${{ parameters.environment }}"
        displayName: "Export - ${{ parameters.solutionName }}"

      - task: PowerAppsUnpackSolution@0
        inputs:
          SolutionInputFile: '$(Pipeline.Workspace)\${{ parameters.artifactName }}\packed\${{ parameters.solutionName }}.zip'
          SolutionTargetFolder: '$(Pipeline.Workspace)\${{ parameters.artifactName }}\unpacked\${{ parameters.solutionName }}'
          SolutionType: Unmanaged

      - publish: $(Pipeline.Workspace)/${{ parameters.artifactName }}
        artifact: ${{ parameters.artifactName }}
