parameters:
  artifactName: "solution-artifact"
  environment: ""
  solutionName: ""

jobs:
  - job: Export_${{ parameters.solutionName }}
    pool:
      vmImage: "vs2017-win2016"

    steps:
      - task: PowerAppsToolInstaller@0

      # Could export unmanaged and managed solutiosn via two jobs to make this faster.
      # Export Unmanaged Solution
      - task: PowerAppsExportSolution@0
        inputs:
          SolutionName: "${{ parameters.solutionName }}"
          SolutionOutputFile: '$(Pipeline.Workspace)\${{ parameters.artifactName }}\packed\${{ parameters.solutionName }}.zip'
          PowerAppsEnvironment: "${{ parameters.environment }}"
        displayName: "Export - ${{ parameters.solutionName }}"

      # Export Managed Solution
      - task: PowerAppsExportSolution@0
        inputs:
          SolutionName: "${{ parameters.solutionName }}"
          SolutionOutputFile: '$(Pipeline.Workspace)\${{ parameters.artifactName }}\packed\${{ parameters.solutionName }}_managed.zip'
          PowerAppsEnvironment: "${{ parameters.environment }}"
          Managed: true
        displayName: "Export - ${{ parameters.solutionName }}"

      # Unpack both managed and unmanaged solution
      - task: PowerAppsUnpackSolution@0
        inputs:
          SolutionInputFile: '$(Pipeline.Workspace)\${{ parameters.artifactName }}\packed\${{ parameters.solutionName }}.zip'
          SolutionTargetFolder: '$(Pipeline.Workspace)\${{ parameters.artifactName }}\unpacked\${{ parameters.solutionName }}'
          SolutionType: Both

      - publish: $(Pipeline.Workspace)/${{ parameters.artifactName }}
        artifact: ${{ parameters.artifactName }}
