parameters:
  artifactName: ""
  SolutionName: ""

jobs:
  - job: Unpack_Solutions
    pool:
      VmImage: "vs2017-win2016"

    steps:
      - download: current

      - task: PowerAppsToolInstaller@0

      - task: CopyFiles@2
        inputs:
          SourceFolder: "$(Pipeline.Workspace)/${{ parameters.artifactName }}-${{ parameters.SolutionName }}/unpacked"
          Contents: "**"
          TargetFolder: "$(Build.SourcesDirectory)/solutions"
          OverWrite: true
      - script: |
          Copy-Item -Path "$(Pipeline.Workspace)/${{ parameters.artifactName }}-${{ parameters.SolutionName }}\packed\*" -Destination "$(Build.SourcesDirectory)/solutions" -Recurse
          Copy-Item -Path "$(Pipeline.Workspace)/${{ parameters.artifactName }}-${{ parameters.SolutionName }}_managed\packed\*" -Destination "$(Build.SourcesDirectory)/solutions" -Recurse

      # Unpack both managed and unmanaged solution
      - task: PowerAppsUnpackSolution@0
        inputs:
          SolutionInputFile: '$(Pipeline.Workspace)/${{ parameters.artifactName }}-${{ parameters.SolutionName }}\packed\${{ parameters.SolutionName }}.zip'
          SolutionTargetFolder: '$(Pipeline.Workspace)\${{ parameters.artifactName }}\unpacked\${{ parameters.SolutionName }}'
          SolutionType: Both

      - publish: $(Pipeline.Workspace)/${{ parameters.artifactName }}
        artifact: ${{ parameters.artifactName }}

      - checkout: self
        persistCredentials: true

      # Reattach to branch (variable)
      # Configure user.name and user.email
      - pwsh: |
          git checkout ("$(Build.SourceBranch)" -replace "^refs/heads/", "")
          git config user.name "Automated Pipeline Commit"
          git config user.email "PPALM-Exploration-Build-Account"
        displayName: "Checkout branch and config user"

      - download: current

      - script: |
          git add .
          git commit -m "Automated commit of solutions: ${{ join(', ', parameters.solutions) }}"
          git push
        displayName: "Automated commit of solutions: ${{ join(', ', parameters.solutions) }}"
      # TODO ensure project collection build service accounts has contribute permissions
